### ISSUE TITLE
JavaScript isn't executed when using capybara-webkit

### ISSUE THREAD

**Issue by exupero** [simonrice/middleman-rspec#3]
When using capybara-webkit as the JavaScript driver, JavaScript code in `all.js` is executed, but code in the required files is not. I suspect Sprockets is not processing `all.js` and producing the complete JavaScript file.

I have [a fork of this project](https://github.com/exupero/middleman-rspec) with [a failing test](https://github.com/exupero/middleman-rspec/blob/master/spec/features/index_spec.rb#L19-L22) that demonstrates the problem.

**Comment by seabre** [comment]
Whoa. Thanks @exupero, I've been fighting this for a good bit. This was exactly what I needed to get my tests with JS going.
